sequenceDiagram
    participant browser
    participant server

    Note right of browser: The browser sends a post with the new note

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    
    Note left of server: The server requests a new GET to a new location
    
    server-->>browser: status 302 - redirect to exampleapp/notes
    deactivate server

    Note right of browser: The browser sends the new GET to the new location

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server

    Note left of server: The server answers with the html page 

    server-->>browser: HTML document
    deactivate server

    Note right of browser: The browser requests the css file

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    
    Note left of server: The server sends the css
    
    server-->>browser: CSS file
    deactivate server

    Note right of browser: The browser requests the js file

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    
    Note left of server: The server sends the js

    server-->>browser: JScript file
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "También existen madridistas de izquierdas", "date": "2024-05-28T08:20:28.015Z" }, ... ]
    deactivate server


    Note right of browser: The browser executes the callback function that renders the notes
